functionsDirectory = "/Users/alialperenatici/Desktop/uppsydigital/netlify/functions"
functionsDirectoryOrigin = "config"
redirectsOrigin = "config"
headersOrigin = "inline"
plugins = []

[build]
publish = "/Users/alialperenatici/Desktop/uppsydigital/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "/Users/alialperenatici/Desktop/uppsydigital/netlify/functions"

[build.environment]
NODE_VERSION = "18"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[dev]
command = "npm run dev"
port = 4321.0
publish = "dist"

[images]
remote_images = []

[functions]

[functions."*"]

[[headers]]
for = "/_astro/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
from = "/admin"
to = "/keystatic"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/keystatic/*"
to = "/.netlify/functions/keystatic/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]