[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/admin"
  to = "/keystatic"
  status = 301
  force = true

[[redirects]]
  from = "/keystatic/*"
  to = "/.netlify/functions/keystatic/:splat"
  status = 200
